RF | _PipelineTest > refactoring tests, methods, and removing constants
SergeiDemyanenko/JenkinsQA_04 pull request #1094
Opened 2022-06-28 20:44 UTC by patriotby07

https://trello.com/c/q1UWGFYj/954-rf-pipelinetest-refactoring-tests-methods-and-removing-constants

2022-06-28 22:53 UTC, AnastasiiaPV approved these changes

2022-06-29 00:12 UTC, GitForProjects requested changes

2022-06-29 00:12 UTC, GitForProjects commented on src/test/java/_PipelineTest.java
>      private void homePageClick() {
instead of creating this method you can use the existing ProjectUtils method : 
ProjectUtils.Dashboard.Header.Dashboard.click(getDriver());

2022-06-29 00:12 UTC, GitForProjects commented on src/test/java/_PipelineTest.java
>          createPipeline(name, Boolean.TRUE);
you can use ProjectUtils.createProject - to create new pipeline

2022-06-29 05:13 UTC, patriotby07 commented on src/test/java/_PipelineTest.java
>      private void homePageClick() {
Thanks, fixed it

2022-06-29 05:13 UTC, patriotby07 commented on src/test/java/_PipelineTest.java
>          createPipeline(name, Boolean.TRUE);
Thanks, fixed it

2022-06-29 05:40 UTC, AlekseiChapaev approved these changes

2022-06-29 05:41 UTC, merged