Added abstract class HeaderFooterPage and extended it by the classes
SergeiDemyanenko/JenkinsQA_04 pull request #1138
Opened 2022-07-03 02:51 UTC by tatauch

Added abstract class HeaderFooterPage and extended it by the following classes
HomePage
NewItemPage
PeoplePage
BuildHistoryPage
ManageJenkinsPage
NewViewPage
MyViewPage

Refactoring to POM
testIsHeaderDisplayedOnTopOnNewItemPage
testIsHeaderDisplayedOnTopOnPeoplePage
testIsHeaderDisplayedOnTopOnBuildHistoryPage
testIsHeaderDisplayedOnTopOnManageJenkinsPage
testIsHeaderDisplayedOnTopOnNewViewPage
testIsHeaderDisplayedOnTopOnMyViewPage

2022-07-03 04:41 UTC, ValeriiSarukhanov commented on src/test/java/model/HeaderFooterPage.java
> +public abstract class HeaderFooterPage extends BasePage{
Почему класс Абстрактный?

2022-07-03 05:23 UTC, tatauch commented
> В этом PR добавляются новые POM, пустые POM. Не вижу в этом смысла.

Я посмотрела, что в тестах эти страницы будут использоваться, в них перенесут локаторы и методы.
Но если отталкиваться только от того, что уже перенесено, то можно сделать FooterHeader необстрактным и возвращать клики на этот класс. 
Например так.
public HeaderFooterPage clickMyViews() {
        myViews.click();

        return new HeaderFooterPage(getDriver());
    }
    Так можно?

2022-07-03 18:23 UTC, tatauch commented
> В этом PR добавляются новые POM, пустые POM. Не вижу в этом смысла.

Обновила, сейчас нету пустых POM

2022-07-04 20:41 UTC, ke-de-ve requested changes

2022-07-04 20:41 UTC, ke-de-ve commented on src/test/java/_HeaderTest.java
> +        NewItemPage isHeaderDisplayed = new HomePage(getDriver())
isHeaderDisplayed  странное имя для переменной класса NewItemPage .  
Почему не  newItemPage ?   

вот так по-моему более понятно что происходит:

    public void testIsHeaderDisplayedOnTopOnNewItemPage() {
        NewItemPage newItemPage = new HomePage(getDriver())
                .clickNewItem();

        Assert.assertTrue(newItemPage.getPageHeader().isDisplayed());
        Assert.assertEquals(newItemPage.getPageHeaderLocation(), "(0, 0)");
    }
    
и все тесты ниже с такой же проблемой

2022-07-04 20:41 UTC, ke-de-ve commented on src/test/java/_HeaderTest.java
> +        PeoplePage isHeaderDisplayed = new HomePage(getDriver())
смотри выше

2022-07-04 20:41 UTC, ke-de-ve commented on src/test/java/_HeaderTest.java
> +        BuildHistoryPage isHeaderDisplayed = new HomePage(getDriver())
смотри выше

2022-07-04 20:41 UTC, ke-de-ve commented on src/test/java/_HeaderTest.java
> +        ManageJenkinsPage isHeaderDisplayed = new HomePage(getDriver())
смотри выше

2022-07-04 20:41 UTC, ke-de-ve commented on src/test/java/_HeaderTest.java
> +        MyViewPage isHeaderDisplayed = new HomePage(getDriver())
смотри выше

2022-07-04 20:41 UTC, ke-de-ve commented on src/test/java/_HeaderTest.java
> +        NewViewPage isHeaderDisplayed = new HomePage(getDriver())
смотри выше

2022-07-04 20:41 UTC, ke-de-ve commented on src/test/java/model/BuildHistoryPage.java
> +
лишние строки

2022-07-04 23:04 UTC, tatauch commented
https://github.com/SergeiDemyanenko/JenkinsQA_04/pull/1162
Учла все замечания и исправила. Сделала отдельный комит, касающийся только тестов из HeaderTests

2022-07-05 03:06 UTC, closed without merging