RF | _FreestyleTest refactored two tests.
SergeiDemyanenko/JenkinsQA_04 pull request #1220
Opened 2022-07-12 13:59 UTC by azellus-tercia

Refactored tests: testConfigureSaveButton and testConfigureApplyButton.
Changed dependencies.

2022-07-12 14:12 UTC, azellus-tercia commented
![](https://github.trello.services/images/mini-trello-icon.png) [RF | _FreestyleTest > refactored two tests.](https://trello.com/c/8HZQTpmt/1081-rf-freestyletest-refactored-two-tests)

2022-07-12 17:17 UTC, Stanislaw1349 approved these changes
LGFM

2022-07-12 17:43 UTC, Valerii-Sarukhanov commented on src/test/java/_FreestyleTest.java
> +    public void testConfigureSaveButton() {
В чём смысл этого теста?
Тест testAddDescription покрывает целиком этот тест и решает свою задачу.
Обсуждаемый тест необходимо просто удалить (у меня ещё не дошли руки до него).

2022-07-12 18:18 UTC, azellus-tercia commented on src/test/java/_FreestyleTest.java
> +    public void testConfigureSaveButton() {
Тест, согласно user story, проверяет работоспособность кнопок Save и Apply после создания проекта. В данном случае - перенаправление на страницу проекта после нажатия на кнопку Save. В тесте testAddDescription проверяется изменение описания проекта и его корректное отображение.

2022-07-12 18:24 UTC, Valerii-Sarukhanov commented on src/test/java/_FreestyleTest.java
> +    public void testConfigureSaveButton() {
Хорошо.
В этом случае testCreateFreestyleProject решает задачу обсуждаемого теста.

2022-07-12 18:30 UTC, azellus-tercia commented on src/test/java/_FreestyleTest.java
> +    public void testConfigureSaveButton() {
Разумеется. Там проект создается, здесь - уже создан. Немного разные начальные условия.
Если это не считается достаточным изменением, тогда я могу удалить этот тест.

2022-07-12 18:34 UTC, ValeriiSarukhanov approved these changes

2022-07-12 18:34 UTC, azellus-tercia commented on src/test/java/_FreestyleTest.java
> +    public void testConfigureSaveButton() {
https://trello.com/c/z4D7sJGZ/385-us005a-freestyle-project-configure-check-for-buttons-save-and-apply
Сама user story, для удобства.

2022-07-12 18:37 UTC, ValeriiSarukhanov commented on src/test/java/_FreestyleTest.java
> +    public void testConfigureSaveButton() {
Очень странно.
Просто нажать на кнопки...
И никаких действий.
Хорошо, я одобрил.

2022-07-13 13:24 UTC, ValeriiSarukhanov requested changes

2022-07-13 16:23 UTC, azellus-tercia commented on src/test/java/model/FreestyleConfigPage.java
> +    private static final By APPLY_ALERT = By.id("notification-bar");
А в чем, собственно, проблема?

2022-07-13 16:32 UTC, ValeriiSarukhanov commented on src/test/java/model/FreestyleConfigPage.java
> +    private static final By APPLY_ALERT = By.id("notification-bar");
Проблема в локаторе. Нет возможности прописать его так-же как и остальные локаторы на этой странице?

2022-07-13 17:12 UTC, ValeriiSarukhanov approved these changes

2022-07-13 17:31 UTC, merged