RF | _HeaderTest > testHeaderLogoIsClickableOnAllPagesToHomepage
SergeiDemyanenko/JenkinsQA_04 pull request #1286
Opened 2022-07-18 22:11 UTC by MariaShy

https://trello.com/c/xI0SK8iH/1110-rf-headertest-testheaderlogoisclickableonallpagestohomepage

2022-07-18 22:12 UTC, sashokdzr approved these changes

2022-07-18 23:30 UTC, tatauch requested changes

2022-07-18 23:30 UTC, tatauch commented on src/test/java/model/HomePage.java
> +    @FindBy(id="jenkins-home-link")
Этот элемент нужно перенести в BaseDashboardPage

2022-07-18 23:30 UTC, tatauch commented on src/test/java/_HeaderTest.java
>      public void testHeaderLogoIsClickableOnAllPagesToHomepage(){
В том виде, в котором сейчас написан тест - это не РОМ. По аналогии с другими тестами из этого класса, нужно этот тест разбить на 7 отдельных тестов.
Все методы и локаторы к этим тестам должны быть в BaseDashboardPage

2022-07-19 03:43 UTC, Stanislaw1349 approved these changes
LGFM

2022-07-19 06:01 UTC, MariaShy commented on src/test/java/model/HomePage.java
> +    @FindBy(id="jenkins-home-link")
спасибо, действительно, в HomePage ему не место. единственное. перенесла не в BaseDashboardPage, а в BaseHeaderFooterPage, поскольку этот элемент есть всегда даже там, где нет дашборда.

2022-07-19 06:04 UTC, MariaShy commented on src/test/java/_HeaderTest.java
>      public void testHeaderLogoIsClickableOnAllPagesToHomepage(){
давайте обсудим на стендапе. По моему мнению, проект должен быть гибким, и нельзя 2 компактные строчки кода умножать на 6 только в угоду идеологии POM: если эти 2 строчки кода всем понятны и никому не мешают, то почему их нужно менять?

2022-07-19 07:42 UTC, tatauch approved these changes

2022-07-19 19:41 UTC, RusAli commented
![](https://github.trello.services/images/mini-trello-icon.png) [RF | _HeaderTest > testVerifyImageOrderOnAllPages](https://trello.com/c/THb0xB4n/1104-rf-headertest-testverifyimageorderonallpages)

2022-07-20 13:53 UTC, closed without merging