RF | __HeaderTest >testCheckExpandMenuBuilds(), testCheckExpandMenuConfigure(), testCheckExpandMenuMyViews().
SergeiDemyanenko/JenkinsQA_04 pull request #1315
Opened 2022-07-21 22:17 UTC by olpolezhaeva

Delete unused:
 -private WebElement configure,
 -private WebElement builds
 from class BaseHeaderFooterPag.
 
Refactoring :
-testCheckExpandMenuBuilds(),
-testCheckExpandMenuConfigure(),
-testCheckExpandMenuMyViews().

2022-07-22 13:45 UTC, ke-de-ve requested changes

2022-07-22 13:45 UTC, ke-de-ve commented on src/test/java/_HeaderTest.java
> +        Assert.assertEquals(buttonText,"Add new Token");
add space between parameters

2022-07-22 13:45 UTC, ke-de-ve commented on src/test/java/_HeaderTest.java
> +        Assert.assertEquals(myViewsText,"My Views");
add space between parameters

2022-07-22 13:45 UTC, ValeriiSarukhanov approved these changes

2022-07-22 14:19 UTC, olpolezhaeva commented on src/test/java/_HeaderTest.java
> +        Assert.assertEquals(myViewsText,"My Views");
Ok,Thanks!

2022-07-22 15:37 UTC, azellus-tercia approved these changes

2022-07-22 19:01 UTC, olpolezhaeva commented
![](https://github.trello.services/images/mini-trello-icon.png) [RF | __HeaderTest >testCheckExpandMenuBuilds(), testCheckExpandMenuConfigure(), testCheckExpandMenuMyViews().](https://trello.com/c/3DBQjluN/1200-rf-headertest-testcheckexpandmenubuilds-testcheckexpandmenuconfigure-testcheckexpandmenumyviews)

2022-07-23 18:56 UTC, ke-de-ve approved these changes

2022-07-23 19:30 UTC, merged