testKseniyaTitovaDelishSignIn
SergeiDemyanenko/JenkinsQA_04 pull request #171
Opened 2022-05-18 18:11 UTC by ksutitova

KseniyaTitova

2022-05-18 19:24 UTC, Stanislaw1349 commented
Зачем что-то менять в классе BaseUtils?

2022-05-18 19:34 UTC, Stanislaw1349 commented on src/test/java/runner/BaseUtils.java
> -public final class BaseUtils {
вернуть как было

2022-05-18 19:34 UTC, Stanislaw1349 commented on src/test/java/runner/BaseUtils.java
> -                        System.out.println("You need to create it from local.properties.TEMPLATE file.");
и здесь тоже

2022-05-18 19:42 UTC, azellus-tercia reviewed
Отмените, пожалуйста, изменения и удаление файлов BaseUtils.java и local.properties.TEMPLATE.

2022-05-18 19:52 UTC, ksutitova commented on src/test/java/runner/BaseUtils.java
> -                        System.out.println("You need to create it from local.properties.TEMPLATE file.");
Извиняюсь, вышло случайно, не видела изменений

2022-05-18 19:52 UTC, ksutitova commented on src/test/java/runner/BaseUtils.java
> -public final class BaseUtils {
все исправила, проверьте, пожалуйста

2022-05-18 20:02 UTC, Stanislaw1349 commented on src/test/java/runner/BaseUtils.java
> -                        System.out.println("You need to create it from local.properties.TEMPLATE file.");
для учебы это даже полезно

2022-05-18 20:06 UTC, Stanislaw1349 commented
Как исправите, запуште изменения в этот же PR

2022-05-18 20:07 UTC, ksutitova commented on src/test/java/runner/BaseUtils.java
> -                        System.out.println("You need to create it from local.properties.TEMPLATE file.");
спасибо, буду внимательней

2022-05-18 20:12 UTC, Stanislaw1349 commented
отмените удаление файла     src/test/resources/local.properties.TEMPLATE

2022-05-18 21:56 UTC, RusAli requested changes

2022-05-18 21:56 UTC, RusAli commented on src/test/resources/local.properties.TEMPLATE
> -default.chrome_options=--window-size=1920,1080
это файл трогать нельзя

2022-05-18 21:56 UTC, RusAli commented on src/test/java/runner/KseniyaTestDelish.java
> +
лишний пробел

2022-05-18 21:56 UTC, RusAli commented on src/test/java/runner/KseniyaTestDelish.java
> +
здесь тоже лишний пробел

2022-05-23 18:44 UTC, closed without merging

2022-05-23 18:45 UTC, Stanislaw1349 commented
автор теста создал новый PR с исправлениями