Add files via upload
SergeiDemyanenko/JenkinsQA_04 pull request #192
Opened 2022-05-20 01:34 UTC by VickyP13

2022-05-20 05:02 UTC, anonymoustuna reviewed
LGTM

2022-05-20 05:03 UTC, anonymoustuna approved these changes

2022-05-20 05:14 UTC, Smirnova-Katya approved these changes

2022-05-20 05:33 UTC, Smirnova-Katya requested changes

2022-05-20 05:33 UTC, Smirnova-Katya commented on src/test/java/testQaSoCalVictoria.java
> +public class testQaSoCalVictoria {
Class testQaSoCalVictoria should be extended from BaseTest

2022-05-20 05:33 UTC, Smirnova-Katya commented on src/test/java/testQaSoCalVictoria.java
> +        WebDriver driver = new ChromeDriver();
It's not necessary cause we have a driver manager. You can use getDriver() from BaseTest

2022-05-20 05:33 UTC, Smirnova-Katya commented on src/test/java/testQaSoCalVictoria.java
> +        addToCartBtn.click();
If you use a variable just once, there is no point to create a variable
```suggestion
        driver.findElement(By.id("add-to-cart-sauce-labs-backpack")).click();

```

2022-05-20 05:33 UTC, Smirnova-Katya commented on src/test/java/testQaSoCalVictoria.java
> +        addedToCardBtn.click();
The same as an above

2022-05-20 22:15 UTC, VickyP13 commented on src/test/java/testQaSoCalVictoria.java
> +        addedToCardBtn.click();
changed

2022-05-20 22:15 UTC, VickyP13 commented on src/test/java/testQaSoCalVictoria.java
> +        addToCartBtn.click();
changed

2022-05-21 03:32 UTC, VickyP13 commented on src/test/java/testQaSoCalVictoria.java
> +public class testQaSoCalVictoria {
ok

2022-05-21 23:44 UTC, closed without merging