Add new tests
SergeiDemyanenko/JenkinsQA_04 pull request #220
Opened 2022-05-22 01:00 UTC by Rom-T

2022-05-22 07:35 UTC, ShurikGr requested changes

2022-05-22 07:35 UTC, ShurikGr commented on src/test/java/RomanTest.java
> +        getDriver().findElement(By.xpath("//p[@id='add_to_cart']")).click();
Судя по тесту CI - программа не может найти элемент по этому xPath

2022-05-22 14:41 UTC, Rom-T commented on src/test/java/RomanTest.java
> +        getDriver().findElement(By.xpath("//p[@id='add_to_cart']")).click();
На локальной машине проходят тесты, а тут почему-то не может найти элемент. Я уже часть дополнительных элементов удалил из кода из-за этого. Продолжаю искать причину. Сегодня попробую прописать полный xPath.

2022-05-24 16:40 UTC, anonymoustuna approved these changes
LGTM

2022-05-24 16:40 UTC, anonymoustuna commented on src/test/java/RomanTest.java
> +
You might get rid of some empty lines maybe.

2022-05-25 01:59 UTC, ShurikGr approved these changes

2022-05-25 02:03 UTC, merged