New test Ola
SergeiDemyanenko/JenkinsQA_04 pull request #221
Opened 2022-05-22 04:13 UTC by pojirakula

Please, approve my pull request

2022-05-22 04:15 UTC, GitForProjects approved these changes
LGFM

2022-05-22 07:31 UTC, ShurikGr requested changes
Ваш тест падает

2022-05-22 07:58 UTC, azellus-tercia commented on src/test/java/OlaTest.java
> +        WebElement h1 = getDriver().findElement(By.xpath("//body/div[@id='page']/div[@id='maincontent']/h1"));
Failed tests:   testMvnRepositoryHomePageFindText(OlaTest): no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[@id='page']/div[@id='maincontent']/h1"}(..)

Ошибка, не может найти указанный элемент. Попробуйте изменить тип локатора.

2022-05-22 19:34 UTC, pojirakula commented on src/test/java/OlaTest.java
> +        WebElement h1 = getDriver().findElement(By.xpath("//body/div[@id='page']/div[@id='maincontent']/h1"));
изменила тест, проверки прошли

2022-05-22 19:37 UTC, GitForProjects approved these changes
now it works fine

2022-05-22 19:40 UTC, GitForProjects approved these changes
LGFM

2022-05-22 22:21 UTC, anonymoustuna approved these changes

2022-05-22 22:21 UTC, anonymoustuna commented on src/test/java/OlaTest.java
> +        privacy.click();
Можно было строки 13 и 14 совместить и записать в виде одно строки.

2022-05-23 02:30 UTC, pojirakula commented on src/test/java/OlaTest.java
> +        privacy.click();
учту

2022-05-23 06:13 UTC, azellus-tercia approved these changes

2022-05-23 19:54 UTC, pojirakula reviewed
done

2022-05-23 23:46 UTC, GitForProjects approved these changes
Ok

2022-05-23 23:49 UTC, merged