Karina jenk
SergeiDemyanenko/JenkinsQA_04 pull request #573
Opened 2022-06-03 21:58 UTC by karinka83

first test commit with Jenkins

2022-06-03 22:17 UTC, sabinasaad commented on src/test/java/KarinaKTest.java
> +}
after creating a project you might want to delete it; otherwise the test will fail the next times because project with such name already exists

2022-06-04 02:19 UTC, anonymoustuna approved these changes

2022-06-04 02:19 UTC, anonymoustuna commented on src/test/java/KarinaKTest.java
> +
You might get rid of this empty line.

2022-06-04 03:58 UTC, EvgeniyaPiskunova requested changes

2022-06-04 03:58 UTC, EvgeniyaPiskunova commented on src/test/java/KarinaKTest.java
> +        Boolean expectedResult = folderSubmit.toString().contains("Hello World");
these both statements needs to be converted to Assertions

2022-06-04 03:58 UTC, EvgeniyaPiskunova commented on src/test/java/KarinaKTest.java
> +        Assert.assertEquals(actualResult,expectedResult);
false and false comparison will return true, which is a bug

2022-06-04 03:58 UTC, EvgeniyaPiskunova commented on src/test/java/KarinaKTest.java
> +        Boolean expectedResult = folderSubmit.toString().contains("Hello World");
to match the visible text on web-element function `getText()` must be used

2022-06-10 14:13 UTC, karinka83 commented
branch is cancelled

2022-06-10 14:13 UTC, closed without merging