Vs 004
SergeiDemyanenko/JenkinsQA_04 pull request #576
Opened 2022-06-04 02:22 UTC by ValeriiSarukhanov

2022-06-04 03:10 UTC, VitaliiArtemenko approved these changes
LGTM

2022-06-04 03:50 UTC, EvgeniyaPiskunova requested changes

2022-06-04 03:50 UTC, EvgeniyaPiskunova commented on src/test/java/CreateFreestyleProjectWithoutDescription.java
> +        submitButton();
it looks weird submitting a form 3x times causes different results after every click

2022-06-04 03:50 UTC, EvgeniyaPiskunova commented on src/test/java/CreateFreestyleProjectWithoutDescription.java
> +        Assert.assertTrue(getDriver().findElement(By.xpath("//form[not(contains(text(), 'This project is currently disabled'))]")).isEnabled());
any page which does not contains this text will return something. It is better to find some existing evidences of success.

2022-06-04 03:56 UTC, ValeriiSarukhanov commented on src/test/java/CreateFreestyleProjectWithoutDescription.java
> +        submitButton();
Try run this test.

2022-06-04 03:57 UTC, ValeriiSarukhanov commented on src/test/java/CreateFreestyleProjectWithoutDescription.java
> +        Assert.assertTrue(getDriver().findElement(By.xpath("//form[not(contains(text(), 'This project is currently disabled'))]")).isEnabled());
Sure, I'll put another locator, if you'll approve it.

2022-06-04 04:58 UTC, VitaliiArtemenko commented on src/test/java/CreateFreestyleProjectWithoutDescription.java
> +        submitButton();
It's a common cause to have the same button with the same selector but on different pages. So, he's going through pages by clicking only one button. His expected result is on the third page. That's why he should click this button three times.

2022-06-04 05:49 UTC, EvgeniyaPiskunova commented on src/test/java/CreateFreestyleProjectWithoutDescription.java
> +        Assert.assertTrue(getDriver().findElement(By.xpath("//form[not(contains(text(), 'This project is currently disabled'))]")).isEnabled());
please make changes in this PR

2022-06-04 05:50 UTC, EvgeniyaPiskunova commented on src/test/java/CreateFreestyleProjectWithoutDescription.java
> +        submitButton();
thank you for the clarification

2022-06-04 09:47 UTC, RuslanG13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AT_008 | Pipeline > Create Pipeline](https://trello.com/c/ltC3YCJt/253-at008-pipeline-create-pipeline)

2022-06-04 13:12 UTC, ValeriiSarukhanov commented
> 

What is the question?

2022-06-05 01:53 UTC, ValeriiSarukhanov commented on src/test/java/CreateFreestyleProjectWithoutDescription.java
> +        Assert.assertTrue(getDriver().findElement(By.xpath("//form[not(contains(text(), 'This project is currently disabled'))]")).isEnabled());
Done

2022-06-05 04:27 UTC, EvgeniyaPiskunova approved these changes

2022-06-05 04:44 UTC, merged