Screenshot Feature added
SergeiDemyanenko/JenkinsQA_04 pull request #658
Opened 2022-06-07 19:20 UTC by GitForProjects

@SergeiDemyanenko 
PLease check Screnshot Feature

2022-06-07 19:40 UTC, SergeiDemyanenko requested changes

2022-06-07 19:40 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +    public void getResult(ITestResult result) {
Зачем это было сделано?

2022-06-07 19:40 UTC, SergeiDemyanenko commented on src/test/java/runner/CaptureScreenShot.java
> +    public static String captureScreenFile(WebDriver driver, Status status, String screenName)
Зачем параметр status?

2022-06-07 19:40 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +        {
У нас всегда скобка на той же строке, что и начало конструкции.

2022-06-07 19:40 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +        driver.manage().window().maximize();
Это делать нельзя т.к. в настройка выставляется разрешение и все подобные вещи у нас указываются в настройках.

2022-06-07 19:40 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +    public WebDriver driver;
Зачем это было сделано?

2022-06-07 19:40 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +}
Зачем это было сделано?

2022-06-07 19:40 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseUtils.java
> +                        System.out.println("You need to create it from local.properties file.");
Зачем это было сделано?

2022-06-07 19:40 UTC, SergeiDemyanenko commented on src/test/java/runner/CaptureScreenShot.java
> +    public static String generateFileName(ITestResult result)
Зачем передавать result, если из него нужно только name, может сразу name и передать?

2022-06-07 20:14 UTC, GitForProjects commented on src/test/java/runner/BaseTest.java
> +    public void getResult(ITestResult result) {
вернул protected

2022-06-07 20:14 UTC, GitForProjects commented on src/test/java/runner/CaptureScreenShot.java
> +    public static String captureScreenFile(WebDriver driver, Status status, String screenName)
убрал. Это я логирование там пытался еще добавить, пока не получилось )

2022-06-07 20:15 UTC, GitForProjects commented on src/test/java/runner/BaseTest.java
> +        {
исправил

2022-06-07 20:15 UTC, GitForProjects commented on src/test/java/runner/BaseTest.java
> +        driver.manage().window().maximize();
исправил

2022-06-07 20:15 UTC, GitForProjects commented on src/test/java/runner/BaseTest.java
> +    public WebDriver driver;
исправил

2022-06-07 20:17 UTC, GitForProjects commented on src/test/java/runner/BaseTest.java
> +}
здесь не пойму почему там получается. Вроде сейчас вернул как было, все равно показывает как удто строка лишняя

2022-06-07 20:17 UTC, GitForProjects commented on src/test/java/runner/BaseUtils.java
> +                        System.out.println("You need to create it from local.properties file.");
исправил

2022-06-07 20:18 UTC, GitForProjects commented on src/test/java/runner/BaseTest.java
> +    public static String reportFolder = "\\TestResults\\"+sdf.format(timestamp)+"\\";
забыл что с нуля запускается проект каждый раз. Исправил.
и создание папки с датой запуска тоже убрал

2022-06-07 20:18 UTC, GitForProjects commented on src/test/java/runner/CaptureScreenShot.java
> +    public static String generateFileName(ITestResult result)
исправил

2022-06-07 20:36 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +    public void getResult(ITestResult result) {
еще и имя метода стоит вернуть

2022-06-07 20:47 UTC, SergeiDemyanenko requested changes
Есть еще один вопрос - что потом с файлом делать если ошибка была на сервере, как его получить?

У меня еть решение, но может ты что-то уже придумал?

2022-06-07 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +    public static String reportFolder = "\\TestResults\\";
1. ститические поля всегда идует первыми в классе
2. если ты это поле используешь в другом классе, то может там его и сделать?
3. лучше использовать более универсальные разделители для пути файла (не \, а /)

2022-06-07 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/CaptureScreenShot.java
> +    private static final DateFormat dateFormat = new SimpleDateFormat("yyyy_MM_dd SSS");
для чего жто поле?

2022-06-07 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/CaptureScreenShot.java
> +    {
скобка на другую строку

2022-06-07 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/CaptureScreenShot.java
> +    public static String captureScreen(WebDriver driver, String screenName)
где используется этот метод?

2022-06-07 20:56 UTC, GitForProjects commented
> 

с каким файлом?

2022-06-07 21:07 UTC, GitForProjects commented on src/test/java/runner/BaseTest.java
> +    public static String reportFolder = "\\TestResults\\";
переменную перенес, а как понять "универсальный разделитель"?

2022-06-07 21:07 UTC, GitForProjects commented on src/test/java/runner/CaptureScreenShot.java
> +    private static final DateFormat dateFormat = new SimpleDateFormat("yyyy_MM_dd SSS");
удалил

2022-06-07 21:07 UTC, GitForProjects commented on src/test/java/runner/CaptureScreenShot.java
> +    {
исправил

2022-06-07 21:55 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +    public static String reportFolder = "\\TestResults\\";
я же написал там - не \\, а /

2022-06-07 21:56 UTC, SergeiDemyanenko commented on src/test/java/runner/CaptureScreenShot.java
> +    public static String captureScreen(WebDriver driver, String screenName)
если код не используется, то его стоит удалить

2022-06-07 21:57 UTC, GitForProjects commented on src/test/java/runner/BaseTest.java
> +    public static String reportFolder = "\\TestResults\\";
да, понял. Один символ должен быть оказывается ))
Исправил

2022-06-07 21:58 UTC, GitForProjects commented on src/test/java/runner/CaptureScreenShot.java
> +    public static String captureScreen(WebDriver driver, String screenName)
Ok, удалил

2022-06-07 22:01 UTC, SergeiDemyanenko requested changes
В классе CaptureScreenShot.java только один метод и больше не будет. может стоит этот метод добавить в BaseUtils.java и не создавать дополнительных кассов?

2022-06-07 22:11 UTC, GitForProjects commented on src/test/java/runner/CaptureScreenShot.java
> +    private static final String REPORT_FOLDER = "/ScreenshotsFailure/";
перенес метод в BaseUtils

2022-06-08 00:10 UTC, jbioshock1912 approved these changes

2022-06-08 01:41 UTC, SergeiDemyanenko approved these changes

2022-06-08 03:01 UTC, merged